// Hyp ("Enterprise" API / formerly CardCom) payment gateway client.
//
// Every checkout is created by an admin (see server/routes/admin.js
// generateBillingLink) — there is no public checkout-initiation route.
// Once a client pays, the browser lands on the public, unauthenticated
// GET /api/billing/redirect route, which is only trustworthy because the
// responseMac it carries is keyed by the merchant password: a value the
// client's browser cannot forge. That MAC check (verifyResponseMac) is the
// sole activation trigger for a subscription — see billing.js.
//
// Recurring monthly charges (server/routes/cron.js runBilling) call doDeal
// directly with a stored card token — no redirect, no MAC needed, since we
// initiate that call ourselves with our own credentials.
const crypto = require('crypto');
const { XMLParser } = require('fast-xml-parser');

// parseTagValue: false — Hyp's result/status codes are zero-padded strings
// ("000", "004"); fast-xml-parser's default number coercion would turn them
// into 0 and 4, silently losing the leading zeros the codes actually mean.
const xmlParser = new XMLParser({ ignoreAttributes: false, parseTagValue: false });

// XML-escape values we interpolate into the request. All fields we send are
// generated by us (amounts, IDs, URLs we build) rather than raw user input,
// but escaping is cheap insurance against a malformed terminal/mid value
// breaking the XML structure.
function esc(value) {
  return String(value ?? '').replace(/[&<>"']/g, (c) => ({
    '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&apos;',
  }[c]));
}

function buildTxnSetupXml({ terminalNumber, mid, uniqueid, total, successUrl, errorUrl, cancelUrl }) {
  return `<ashrait>
  <request>
    <version>2000</version>
    <language>ENG</language>
    <command>doDeal</command>
    <doDeal>
      <terminalNumber>${esc(terminalNumber)}</terminalNumber>
      <cardNo>CGMPI</cardNo>
      <total>${esc(total)}</total>
      <transactionType>Debit</transactionType>
      <creditType>RegularCredit</creditType>
      <currency>ILS</currency>
      <transactionCode>Internet</transactionCode>
      <validation>TxnSetup</validation>
      <mid>${esc(mid)}</mid>
      <uniqueid>${esc(uniqueid)}</uniqueid>
      <mpiValidation>AutoComm</mpiValidation>
      <successUrl>${esc(successUrl)}</successUrl>
      <errorUrl>${esc(errorUrl)}</errorUrl>
      <cancelUrl>${esc(cancelUrl || errorUrl)}</cancelUrl>
    </doDeal>
  </request>
</ashrait>`;
}

// Recurring charge against a previously tokenized card — merchant-initiated,
// no customer present, so transactionCode is Phone (matches Hyp's own
// capture-after-authorization example, the closest analogous "customer not
// present" flow in their docs).
function buildRecurringDebitXml({ terminalNumber, cardId, cardExpiration, total }) {
  return `<ashrait>
  <request>
    <version>2000</version>
    <language>ENG</language>
    <command>doDeal</command>
    <doDeal>
      <terminalNumber>${esc(terminalNumber)}</terminalNumber>
      <cardId>${esc(cardId)}</cardId>
      <cardExpiration>${esc(cardExpiration)}</cardExpiration>
      <total>${esc(total)}</total>
      <transactionType>RecurringDebit</transactionType>
      <creditType>RegularCredit</creditType>
      <currency>ILS</currency>
      <transactionCode>Phone</transactionCode>
      <validation>AutoComm</validation>
    </doDeal>
  </request>
</ashrait>`;
}

// POSTs to Hyp's Relay endpoint and returns the parsed doDeal response.
// Throws only on transport/parse failure — a declined transaction is a
// normal response (non-"000" result), not an exception, so callers must
// check the returned result code themselves.
async function callHyp(xml) {
  const params = new URLSearchParams({
    user: process.env.HYP_API_USER || '',
    password: process.env.HYP_API_PASSWORD || '',
    int_in: xml,
  });

  const res = await fetch(process.env.HYP_ENDPOINT, {
    method: 'POST',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
    body: params.toString(),
  });
  const text = await res.text();
  const parsed = xmlParser.parse(text);
  const response = parsed?.ashrait?.response;
  if (!response) throw new Error('Unexpected Hyp response shape');

  return {
    result: String(response.result ?? ''),
    message: response.userMessage || response.message || '',
    tranId: response.tranId,
    doDeal: response.doDeal || {},
  };
}

// Per Hyp's "Transaction Validation" docs: concatenate password + txId +
// (errorCode or "000") + cardToken + cardExp + personalId + uniqueId (empty
// string for any missing field), SHA-256 the result, and base64-encode.
function computeResponseMac({ password, txId, errorCode, cardToken, cardExp, personalId, uniqueId }) {
  const material = [
    password || '',
    txId || '',
    errorCode || '000',
    cardToken || '',
    cardExp || '',
    personalId || '',
    uniqueId || '',
  ].join('');
  return crypto.createHash('sha256').update(material, 'utf8').digest('base64');
}

function verifyResponseMac(fields, responseMac) {
  const expected = Buffer.from(computeResponseMac(fields));
  const actual = Buffer.from(responseMac || '');
  if (expected.length !== actual.length) return false;
  return crypto.timingSafeEqual(expected, actual);
}

module.exports = { buildTxnSetupXml, buildRecurringDebitXml, callHyp, computeResponseMac, verifyResponseMac };
